### ISSUE TITLE
Example repos?

### ISSUE THREAD

**Issue by philmetzger** [marceljuenemann/rxdb-supabase#11]
Hey, Came across this and exactly what I need for a new project I am working on.

However im very new to rxDB and struggling to understand how to use this to make my app offline first.

I was wondering if there are any full example repos I could have a look at?

**Comment by marceljuenemann** [comment]
There are a lot of examples on how to use RxDB in your app here: https://github.com/pubkey/rxdb/tree/master/examples

Once you understand how to build the app with RxDB, just start the replication with Supabase as described in the README of this project
