### ISSUE TITLE
Realtime changes issues?

### ISSUE THREAD

**Issue by philmetzger** [marceljuenemann/rxdb-supabase#12]
I am wondering if listenting to realtime changes really works?

Because I opened up to browsers. In 1 I create a row in a table. Then I expect to see that row in the other browser in my indexdb however i dont see anything. Only when I refresh the whole page.
I even clicked "Refresh" for the docs in my rxDB table but still doesnt show the new row unless I refresh the whole page.

Any ideas?

Its configured like this:
```
new SupabaseReplication({
      supabaseClient: supabase,
      collection: collections.notes,
      replicationIdentifier: `https://${getEnvironmentVariable('SUPABASE_PROJECT_REF')}.supabase.co`,
      pull: {
        lastModifiedField: 'updated_at',
      },
      push: {},
    });
```

**Comment by marceljuenemann** [comment]
Have you enabled realtime in your supabase console?
