### ISSUE TITLE
Issue with tables that primary key is of type uuid in Supabase

### ISSUE THREAD

**Issue by cody-lettau** [marceljuenemann/rxdb-supabase#14]
I'm attempting to get this working with a pretty simple Supabase instance where I have several tables that have primary key columns (```id```) that are of type ```uuid```. Unfortunately, it is not working as I continually get errors regarding the queries ran to populate the local rxdb. The issue appears to stem from [[here](https://github.com/marceljuenemann/rxdb-supabase/blob/0dce15cf58bb45b80468d700f58c235785342323/src/supabase-replication.ts#L182)](https://github.com/marceljuenemann/rxdb-supabase/blob/0dce15cf58bb45b80468d700f58c235785342323/src/supabase-replication.ts#L182).

Essentially, it creates a query for each table that includes something along the lines of `id.gt.id` on the initialization, which throws an error (```Invalid input syntax for type uuid: "id"```).

I can work around this by changing my primary key fields to ```text``` type for all of the tables, except my ```profiles``` table, which has the ```id``` referencing the ```auth.users.id``` column (which has a type of ```uuid```) provided by Supabase.

Any pointers on how to get this working?

**Comment by marceljuenemann** [comment]
The error `Invalid input syntax for type uuid: "id"` suggests to me that you're trying to insert the value "id" into the column ID. That would explain why it works if you change the database type (which the client doesn't even know about) to text. So double check your code for that maybe?

**Comment by marceljuenemann** [comment]
Are you sure you don't have a row with value "id" somewhere in your data? Or possibly you had it previously and it's stored as the last primary key now, which breaks when changing the type to uuid. In that case restart the replication with a new replication ID

**Comment by cody-lettau** [comment]
@marceljuenemann I have completely cleared out the databases in the browser each time I try to get it working. I tested with 1 completely empty table, one with ~15 rows (all values in the ```id``` column are valid uuids) and another table with a single user profile where the ```id``` is a valid uuid pointing to the ```auth.users.id``` column. Each of these failed when the column type of ```id``` (primary key column) was ```uuid``` with an auto generated value in Supabase.

Then I changed two of the three tables to have the ```id``` column be of ```text``` type. Those two tables did start to sync fine (again, I cleared out all the databases via the dev console in Chrome before starting the app). The 3rd table (```profiles```) still failed because the ```id``` column could not be changed from ```uuid``` as it was a foreign key to the ```auth.users``` table.

![image](https://github.com/marceljuenemann/rxdb-supabase/assets/7740624/5db0c57b-9010-4253-844d-fa454e1bd095)

For example, here is the json-schema being used for the profiles table:
```
const properties = {
      id: {
            type: 'string',
            maxLength: 36,
      },
      full_name: {
            type: 'string',
      },
      avatar_url: {
            type: 'string',
      },
      welcome_complete: {
            type: 'boolean',
      },
};

const schema = {
      title: 'profiles',
      version: 0,
      primaryKey: 'id',
      type: 'object',
      properties,
      required: ['id'],
      indexes: [],
};
```

The ```profiles``` table does have RLS enabled, but this did appear to work on another table with RLS where I changed that primary key field to be of ```text``` type.

**Comment by cody-lettau** [comment]
Here's an example of the call being made to supabase:
```/rest/v1/profiles?select=*&or=%28_modified.gt.%221970-01-01T00%3A00%3A00.000Z%22%2Cand%28_modified.eq.%221970-01-01T00%3A00%3A00.000Z%22%2Cid.gt.%22id%22%29%29&order=_modified.asc%2Cid.asc&limit=100```

**Comment by cody-lettau** [comment]
I ended up just moving to use ```text``` types and modified my schema for now. Not sure what is going on when the type of the primary key field is ```uuid``` in Supabase, but it wasn't working for me. I'll probably circle back when refactoring as I'm not a fan of how the DB schema is setup right now :)

**Comment by cody-lettau** [comment]
Believe I figured it out - in the example I started with it was defining an initial checkpoint and passing that into the ```pull``` options when creating the replication options.
